theme: jekyll-theme-minimal
title: Threat Hunting Writeups


logo: /assets/img/photo-leo.png
description: > 
  Hola, Soy Leo. Si te encuentras aquí, muchas gracias por tomarte el tiempo 
  de visitar mi blog personal. Aquí subiré writeups técnicos sobre 
  ciberseguridad defensiva, llevados no solo desde la teoría sino también desde la practica. 
  espero te sean de ayuda y te puedan orientar si algún dia lo necesites.
author: Leo Jaraba
location: Bogotá, Colombia
github_username: Leo-Jp01
email: leo.jaraba.dev@gmail.com
show_downloads: false