theme: jekyll-theme-minimal
title: Threat Hunting Writeups


logo: /assets/img/photo-leo.png
description: Writeups técnicos de ciberseguridad defensiva con enfoque práctico.
author: Leo Jaraba
location: Bogotá, Colombia
github_username: Leo-Jp01
email: leo.jaraba.dev@gmail.com
show_downloads: false
